USE [master]
GO

/****** Object:  Database [GeracaoDoAmanha]    Script Date: 18/05/2020 22:28:47 ******/
CREATE DATABASE [GeracaoDoAmanha]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GeracaoDoAmanha', FILENAME = N'D:\Database\GeracaoDoAmanha.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GeracaoDoAmanha_log', FILENAME = N'D:\Database\GeracaoDoAmanha_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GeracaoDoAmanha].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GeracaoDoAmanha] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET ARITHABORT OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GeracaoDoAmanha] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GeracaoDoAmanha] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GeracaoDoAmanha] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GeracaoDoAmanha] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GeracaoDoAmanha] SET  MULTI_USER 
GO

ALTER DATABASE [GeracaoDoAmanha] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GeracaoDoAmanha] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GeracaoDoAmanha] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GeracaoDoAmanha] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GeracaoDoAmanha] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GeracaoDoAmanha] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GeracaoDoAmanha] SET  READ_WRITE 
GO

