/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author pedro
 */
	
public class TelaMetas extends javax.swing.JFrame {

    /**
     * Creates new form TelaMetas
     */
    public TelaMetas() {
	initComponents();
	modoInicial();
	criarJLabel();
	jButtonAltPag05.setVisible(false);
    };
    
    Dimension dmnsn0 = new Dimension(0,650);
    Dimension dmnsn1 = new Dimension(1000,650);
    Font font = new Font("Arial", Font.BOLD, 13);
    
    private void criarJLabel(){	
	jLabel1.setText("1.Procure alimentos não-perecíveis na sua despensa e faça uma doação");
	jLabel2.setText("2.Pague uma refeição para alguém que precisa");
	jLabel3.setText("3.Aprenda mais sobre as causas e os sintomas das doenças cardiovasculares assim como sobre Doenças Crônicas Não Transmissíveis");
	jLabel4.setText("4.Apoie instituições filantrópicas que trabalhem com a educação nas regiões mais pobres do mundo");
	jLabel5.setText("5.Apoie entidades que dão o acesso a água potável para populações necessitadas no Brasil");
	jLabel6.setText("6.Apoie entidades que dão o acesso a água potável para populações necessitadas em todo o planeta");
	jLabel7.setText("7.Use lâmpadas fluorescentes e de LED e mude seus hábitos para consumir menos energia");
	jLabel8.setText("8.Torne-se um micro credor e empodere jovens para serem empreendedores");
	jLabel9.setText("9.Incentive as crianças a fazer amizade com crianças de diferentes culturas");
	jLabel10.setText("10.Pesquise, incentive e conscientize as pessoas para obter maior transparência das informações em sua comunidade");
	jLabel11.setText("11.Eduque-se sobre o patrimônio cultural e natural de sua região. Visite locais históricos e publique sobre eles de maneira positiva");
	jLabel12.setText("12.Não guarde roupas ou outros itens que você não estiver usando. Faça uma doação");
	jLabel13.setText("13.Mantenha os banhos curtos. O uso excessivo de água contribui para o estresse hídrico global");
	jLabel14.setText("14.Organize para a sua escola ou empresa plantar novas árvores a cada ano. As árvores fornecem oxigênio e absorvem dióxido de carbono");
	jLabel15.setText("15.Apoie organizações que protegem os oceanos");
	jLabel16.setText("16.Quando você entrar em lojas ou ir em mercados, faça escolhas favoráveis ao meio ambiente");
	jLabel17.setText("17.Seja interessado pelas decisões do governo do seu país e mantenha-se pacífico ao defender o que acredita");
	jLabel18.setText("18.Colabore com organizações que precisam de financiamento em uma área na qual você reconheça a importância");
	jLabel19.setText("19.Compartilhe. Se você vir uma publicação interessante nas redes sociais sobre os direitos das mulheres");
	jLabel20.setText("20.Vacine você e seus filhos. Proteger sua família contra doenças também ajuda a saúde pública");
	
	jLabel1.setFont(font);
	jLabel2.setFont(font);
	jLabel3.setFont(font);
	jLabel4.setFont(font);
	jLabel5.setFont(font);
	jLabel6.setFont(font);
	jLabel7.setFont(font);
	jLabel8.setFont(font);
	jLabel9.setFont(font);
	jLabel10.setFont(font);
	jLabel11.setFont(font);
	jLabel12.setFont(font);
	jLabel13.setFont(font);
	jLabel14.setFont(font);
	jLabel15.setFont(font);
	jLabel16.setFont(font);
	jLabel17.setFont(font);
	jLabel18.setFont(font);
	jLabel19.setFont(font);
	jLabel20.setFont(font);
    }
    

    private void modoInicial(){
	jPanelCol1.setVisible(true);
	jPanelCol1.setPreferredSize(dmnsn1);
	jPanelCol2.setVisible(false);
	jPanelCol2.setPreferredSize(dmnsn0);
	jPanelCol3.setVisible(false);
	jPanelCol3.setPreferredSize(dmnsn0);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(false);
	jPanelCol5.setPreferredSize(dmnsn0);
	resetButtonColor();
	jButtonAltPag01.setBackground(Color.GREEN);
    }
    
    private void resetButtonColor(){
	jButtonAltPag01.setBackground(Color.GRAY);
	jButtonAltPag02.setBackground(Color.GRAY);
	jButtonAltPag03.setBackground(Color.GRAY);
	jButtonAltPag04.setBackground(Color.GRAY);
	jButtonAltPag05.setBackground(Color.GRAY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lblLogoOds = new javax.swing.JLabel();
        lblTituloOds = new javax.swing.JLabel();
        lblAcoes = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jButtonAltPag02 = new javax.swing.JButton();
        jButtonAltPag01 = new javax.swing.JButton();
        jButtonAltPag04 = new javax.swing.JButton();
        jButtonAltPag05 = new javax.swing.JButton();
        jButtonAltPag03 = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelCol1 = new javax.swing.JPanel();
        jPanelLine1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLine2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLine3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelLine4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelLine5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCol2 = new javax.swing.JPanel();
        jPanelLine6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelLine7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelLine8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelLine9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelLine10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelCol3 = new javax.swing.JPanel();
        jPanelLine11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelLine12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelLine13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelLine14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelLine15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelCol4 = new javax.swing.JPanel();
        jPanelLine16 = new javax.swing.JPanel();
        jPanelLine17 = new javax.swing.JPanel();
        jPanelLine18 = new javax.swing.JPanel();
        jPanelLine19 = new javax.swing.JPanel();
        jPanelLine20 = new javax.swing.JPanel();
        jPanelCol5 = new javax.swing.JPanel();
        jPanelLine21 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelLine22 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelLine23 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelLine24 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelLine25 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmMetas"); // NOI18N
        setUndecorated(true);

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.setMaximumSize(new java.awt.Dimension(1000, 100));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(1000, 100));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        lblLogoOds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoOds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/LogoLogin64.png"))); // NOI18N
        lblLogoOds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogoOds.setPreferredSize(new java.awt.Dimension(100, 100));

        lblTituloOds.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTituloOds.setForeground(new java.awt.Color(80, 80, 80));
        lblTituloOds.setText("Metas");

        lblAcoes.setBackground(new java.awt.Color(80, 80, 80));
        lblAcoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAcoes.setForeground(new java.awt.Color(80, 80, 80));
        lblAcoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/home_peg.png"))); // NOI18N
        lblAcoes.setText("Home");
        lblAcoes.setFocusable(false);
        lblAcoes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblAcoes.setMaximumSize(new java.awt.Dimension(100, 100));
        lblAcoes.setMinimumSize(new java.awt.Dimension(100, 100));
        lblAcoes.setPreferredSize(new java.awt.Dimension(230, 100));
        lblAcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcoesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(lblLogoOds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTituloOds, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogoOds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloOds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFooter.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanelFooter.setMinimumSize(new java.awt.Dimension(1000, 50));
        jPanelFooter.setPreferredSize(new java.awt.Dimension(1000, 50));

        jButtonAltPag02.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAltPag02.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonAltPag02.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAltPag02.setText("2");
        jButtonAltPag02.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAltPag02.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag02.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag02.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAltPag02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltPag02ActionPerformed(evt);
            }
        });

        jButtonAltPag01.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAltPag01.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonAltPag01.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAltPag01.setText("1");
        jButtonAltPag01.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAltPag01.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag01.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag01.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAltPag01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltPag01ActionPerformed(evt);
            }
        });

        jButtonAltPag04.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAltPag04.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonAltPag04.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAltPag04.setText("4");
        jButtonAltPag04.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAltPag04.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag04.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag04.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAltPag04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltPag04ActionPerformed(evt);
            }
        });

        jButtonAltPag05.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAltPag05.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonAltPag05.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAltPag05.setText("5");
        jButtonAltPag05.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAltPag05.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag05.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag05.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAltPag05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltPag05ActionPerformed(evt);
            }
        });

        jButtonAltPag03.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAltPag03.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonAltPag03.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAltPag03.setText("3");
        jButtonAltPag03.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAltPag03.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag03.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAltPag03.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAltPag03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltPag03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButtonAltPag01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAltPag02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAltPag03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAltPag04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAltPag05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltPag02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAltPag04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAltPag05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAltPag03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAltPag01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelContent.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanelContent.setMinimumSize(new java.awt.Dimension(1000, 650));
        jPanelContent.setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanelCol1.setBackground(new java.awt.Color(80, 80, 80));
        jPanelCol1.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanelCol1.setMinimumSize(new java.awt.Dimension(0, 650));
        jPanelCol1.setPreferredSize(new java.awt.Dimension(10, 650));

        jPanelLine1.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine1.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(80, 80, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine1Layout = new javax.swing.GroupLayout(jPanelLine1);
        jPanelLine1.setLayout(jPanelLine1Layout);
        jPanelLine1Layout.setHorizontalGroup(
            jPanelLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine1Layout.setVerticalGroup(
            jPanelLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine2.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine2.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine2MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(80, 80, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine2Layout = new javax.swing.GroupLayout(jPanelLine2);
        jPanelLine2.setLayout(jPanelLine2Layout);
        jPanelLine2Layout.setHorizontalGroup(
            jPanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine2Layout.setVerticalGroup(
            jPanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine3.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine3.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine3MouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(80, 80, 80));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine3Layout = new javax.swing.GroupLayout(jPanelLine3);
        jPanelLine3.setLayout(jPanelLine3Layout);
        jPanelLine3Layout.setHorizontalGroup(
            jPanelLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine3Layout.setVerticalGroup(
            jPanelLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine4.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine4.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine4MouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(80, 80, 80));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine4Layout = new javax.swing.GroupLayout(jPanelLine4);
        jPanelLine4.setLayout(jPanelLine4Layout);
        jPanelLine4Layout.setHorizontalGroup(
            jPanelLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine4Layout.setVerticalGroup(
            jPanelLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine5.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine5.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine5MouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(80, 80, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine5Layout = new javax.swing.GroupLayout(jPanelLine5);
        jPanelLine5.setLayout(jPanelLine5Layout);
        jPanelLine5Layout.setHorizontalGroup(
            jPanelLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine5Layout.setVerticalGroup(
            jPanelLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCol1Layout = new javax.swing.GroupLayout(jPanelCol1);
        jPanelCol1.setLayout(jPanelCol1Layout);
        jPanelCol1Layout.setHorizontalGroup(
            jPanelCol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol1Layout.createSequentialGroup()
                .addGroup(jPanelCol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCol1Layout.setVerticalGroup(
            jPanelCol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelCol2.setBackground(new java.awt.Color(80, 80, 80));
        jPanelCol2.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanelCol2.setMinimumSize(new java.awt.Dimension(0, 650));
        jPanelCol2.setPreferredSize(new java.awt.Dimension(10, 650));

        jPanelLine6.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine6.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine6MouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(80, 80, 80));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine6Layout = new javax.swing.GroupLayout(jPanelLine6);
        jPanelLine6.setLayout(jPanelLine6Layout);
        jPanelLine6Layout.setHorizontalGroup(
            jPanelLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine6Layout.setVerticalGroup(
            jPanelLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine7.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine7.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine7MouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(80, 80, 80));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine7Layout = new javax.swing.GroupLayout(jPanelLine7);
        jPanelLine7.setLayout(jPanelLine7Layout);
        jPanelLine7Layout.setHorizontalGroup(
            jPanelLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine7Layout.setVerticalGroup(
            jPanelLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine8.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine8.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine8MouseClicked(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(80, 80, 80));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine8Layout = new javax.swing.GroupLayout(jPanelLine8);
        jPanelLine8.setLayout(jPanelLine8Layout);
        jPanelLine8Layout.setHorizontalGroup(
            jPanelLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine8Layout.setVerticalGroup(
            jPanelLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine9.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine9.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine9MouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(80, 80, 80));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine9Layout = new javax.swing.GroupLayout(jPanelLine9);
        jPanelLine9.setLayout(jPanelLine9Layout);
        jPanelLine9Layout.setHorizontalGroup(
            jPanelLine9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine9Layout.setVerticalGroup(
            jPanelLine9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine10.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine10.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine10MouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(80, 80, 80));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine10Layout = new javax.swing.GroupLayout(jPanelLine10);
        jPanelLine10.setLayout(jPanelLine10Layout);
        jPanelLine10Layout.setHorizontalGroup(
            jPanelLine10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine10Layout.setVerticalGroup(
            jPanelLine10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCol2Layout = new javax.swing.GroupLayout(jPanelCol2);
        jPanelCol2.setLayout(jPanelCol2Layout);
        jPanelCol2Layout.setHorizontalGroup(
            jPanelCol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol2Layout.createSequentialGroup()
                .addGroup(jPanelCol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCol2Layout.setVerticalGroup(
            jPanelCol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLine10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelCol3.setBackground(new java.awt.Color(80, 80, 80));
        jPanelCol3.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanelCol3.setMinimumSize(new java.awt.Dimension(0, 650));
        jPanelCol3.setPreferredSize(new java.awt.Dimension(10, 650));

        jPanelLine11.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine11.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine11MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(80, 80, 80));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine11Layout = new javax.swing.GroupLayout(jPanelLine11);
        jPanelLine11.setLayout(jPanelLine11Layout);
        jPanelLine11Layout.setHorizontalGroup(
            jPanelLine11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine11Layout.setVerticalGroup(
            jPanelLine11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine12.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine12.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine12MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(80, 80, 80));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine12Layout = new javax.swing.GroupLayout(jPanelLine12);
        jPanelLine12.setLayout(jPanelLine12Layout);
        jPanelLine12Layout.setHorizontalGroup(
            jPanelLine12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine12Layout.setVerticalGroup(
            jPanelLine12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine13.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine13.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine13MouseClicked(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(80, 80, 80));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine13Layout = new javax.swing.GroupLayout(jPanelLine13);
        jPanelLine13.setLayout(jPanelLine13Layout);
        jPanelLine13Layout.setHorizontalGroup(
            jPanelLine13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine13Layout.setVerticalGroup(
            jPanelLine13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine14.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine14.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine14MouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(80, 80, 80));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine14Layout = new javax.swing.GroupLayout(jPanelLine14);
        jPanelLine14.setLayout(jPanelLine14Layout);
        jPanelLine14Layout.setHorizontalGroup(
            jPanelLine14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine14Layout.setVerticalGroup(
            jPanelLine14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine15.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine15.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine15MouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(80, 80, 80));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine15Layout = new javax.swing.GroupLayout(jPanelLine15);
        jPanelLine15.setLayout(jPanelLine15Layout);
        jPanelLine15Layout.setHorizontalGroup(
            jPanelLine15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine15Layout.setVerticalGroup(
            jPanelLine15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCol3Layout = new javax.swing.GroupLayout(jPanelCol3);
        jPanelCol3.setLayout(jPanelCol3Layout);
        jPanelCol3Layout.setHorizontalGroup(
            jPanelCol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol3Layout.createSequentialGroup()
                .addGroup(jPanelCol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLine11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCol3Layout.setVerticalGroup(
            jPanelCol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelLine12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLine15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelCol4.setBackground(new java.awt.Color(80, 80, 80));
        jPanelCol4.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanelCol4.setMinimumSize(new java.awt.Dimension(0, 650));
        jPanelCol4.setPreferredSize(new java.awt.Dimension(10, 650));

        jPanelLine16.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine16.setPreferredSize(new java.awt.Dimension(1000, 110));

        javax.swing.GroupLayout jPanelLine16Layout = new javax.swing.GroupLayout(jPanelLine16);
        jPanelLine16.setLayout(jPanelLine16Layout);
        jPanelLine16Layout.setHorizontalGroup(
            jPanelLine16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLine16Layout.setVerticalGroup(
            jPanelLine16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanelLine17.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine17.setPreferredSize(new java.awt.Dimension(1000, 110));

        javax.swing.GroupLayout jPanelLine17Layout = new javax.swing.GroupLayout(jPanelLine17);
        jPanelLine17.setLayout(jPanelLine17Layout);
        jPanelLine17Layout.setHorizontalGroup(
            jPanelLine17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLine17Layout.setVerticalGroup(
            jPanelLine17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanelLine18.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine18.setPreferredSize(new java.awt.Dimension(1000, 110));

        javax.swing.GroupLayout jPanelLine18Layout = new javax.swing.GroupLayout(jPanelLine18);
        jPanelLine18.setLayout(jPanelLine18Layout);
        jPanelLine18Layout.setHorizontalGroup(
            jPanelLine18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLine18Layout.setVerticalGroup(
            jPanelLine18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanelLine19.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine19.setPreferredSize(new java.awt.Dimension(1000, 110));

        javax.swing.GroupLayout jPanelLine19Layout = new javax.swing.GroupLayout(jPanelLine19);
        jPanelLine19.setLayout(jPanelLine19Layout);
        jPanelLine19Layout.setHorizontalGroup(
            jPanelLine19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLine19Layout.setVerticalGroup(
            jPanelLine19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanelLine20.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine20.setPreferredSize(new java.awt.Dimension(1000, 110));

        javax.swing.GroupLayout jPanelLine20Layout = new javax.swing.GroupLayout(jPanelLine20);
        jPanelLine20.setLayout(jPanelLine20Layout);
        jPanelLine20Layout.setHorizontalGroup(
            jPanelLine20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLine20Layout.setVerticalGroup(
            jPanelLine20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCol4Layout = new javax.swing.GroupLayout(jPanelCol4);
        jPanelCol4.setLayout(jPanelCol4Layout);
        jPanelCol4Layout.setHorizontalGroup(
            jPanelCol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol4Layout.createSequentialGroup()
                .addGroup(jPanelCol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLine16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCol4Layout.setVerticalGroup(
            jPanelCol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelLine17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLine20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelCol5.setBackground(new java.awt.Color(80, 80, 80));
        jPanelCol5.setMaximumSize(new java.awt.Dimension(10, 650));
        jPanelCol5.setMinimumSize(new java.awt.Dimension(0, 650));
        jPanelCol5.setPreferredSize(new java.awt.Dimension(900, 650));

        jPanelLine21.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine21.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine21MouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(80, 80, 80));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine21Layout = new javax.swing.GroupLayout(jPanelLine21);
        jPanelLine21.setLayout(jPanelLine21Layout);
        jPanelLine21Layout.setHorizontalGroup(
            jPanelLine21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine21Layout.setVerticalGroup(
            jPanelLine21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine22.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine22.setPreferredSize(new java.awt.Dimension(1000, 110));
        jPanelLine22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLine22MouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(80, 80, 80));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine22Layout = new javax.swing.GroupLayout(jPanelLine22);
        jPanelLine22.setLayout(jPanelLine22Layout);
        jPanelLine22Layout.setHorizontalGroup(
            jPanelLine22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine22Layout.setVerticalGroup(
            jPanelLine22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine23.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine23.setPreferredSize(new java.awt.Dimension(1000, 110));

        jLabel18.setForeground(new java.awt.Color(80, 80, 80));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine23Layout = new javax.swing.GroupLayout(jPanelLine23);
        jPanelLine23.setLayout(jPanelLine23Layout);
        jPanelLine23Layout.setHorizontalGroup(
            jPanelLine23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine23Layout.setVerticalGroup(
            jPanelLine23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine24.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine24.setPreferredSize(new java.awt.Dimension(1000, 110));

        jLabel19.setForeground(new java.awt.Color(80, 80, 80));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine24Layout = new javax.swing.GroupLayout(jPanelLine24);
        jPanelLine24.setLayout(jPanelLine24Layout);
        jPanelLine24Layout.setHorizontalGroup(
            jPanelLine24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine24Layout.setVerticalGroup(
            jPanelLine24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLine25.setBackground(new java.awt.Color(250, 250, 250));
        jPanelLine25.setPreferredSize(new java.awt.Dimension(1000, 110));

        jLabel20.setForeground(new java.awt.Color(80, 80, 80));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setPreferredSize(new java.awt.Dimension(980, 90));

        javax.swing.GroupLayout jPanelLine25Layout = new javax.swing.GroupLayout(jPanelLine25);
        jPanelLine25.setLayout(jPanelLine25Layout);
        jPanelLine25Layout.setHorizontalGroup(
            jPanelLine25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLine25Layout.setVerticalGroup(
            jPanelLine25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLine25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCol5Layout = new javax.swing.GroupLayout(jPanelCol5);
        jPanelCol5.setLayout(jPanelCol5Layout);
        jPanelCol5Layout.setHorizontalGroup(
            jPanelCol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol5Layout.createSequentialGroup()
                .addGroup(jPanelCol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLine21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLine25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCol5Layout.setVerticalGroup(
            jPanelCol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCol5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelLine22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLine24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLine25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addComponent(jPanelCol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCol3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCol5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCol4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCol4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCol3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCol5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltPag03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltPag03ActionPerformed
        resetButtonColor();
	jPanelCol1.setVisible(false);
	jPanelCol1.setPreferredSize(dmnsn0);
	jPanelCol2.setVisible(true);
	jPanelCol2.setPreferredSize(dmnsn1);
	jPanelCol3.setVisible(false);
	jPanelCol3.setPreferredSize(dmnsn0);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(false);
	jPanelCol5.setPreferredSize(dmnsn0);
	jButtonAltPag03.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAltPag03ActionPerformed

    private void jButtonAltPag01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltPag01ActionPerformed
        resetButtonColor();
	jPanelCol1.setVisible(true);
	jPanelCol1.setPreferredSize(dmnsn1);
	jPanelCol2.setVisible(false);
	jPanelCol2.setPreferredSize(dmnsn0);
	jPanelCol3.setVisible(false);
	jPanelCol3.setPreferredSize(dmnsn0);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(false);
	jPanelCol5.setPreferredSize(dmnsn0);
	jButtonAltPag01.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAltPag01ActionPerformed

    private void jButtonAltPag02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltPag02ActionPerformed
        resetButtonColor();
	jPanelCol1.setVisible(false);
	jPanelCol1.setPreferredSize(dmnsn0);
	jPanelCol2.setVisible(false);
	jPanelCol2.setPreferredSize(dmnsn0);
	jPanelCol3.setVisible(true);
	jPanelCol3.setPreferredSize(dmnsn1);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(false);
	jPanelCol5.setPreferredSize(dmnsn0);
	jButtonAltPag02.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAltPag02ActionPerformed

    private void jButtonAltPag04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltPag04ActionPerformed
        resetButtonColor();
	jPanelCol1.setVisible(false);
	jPanelCol1.setPreferredSize(dmnsn0);
	jPanelCol2.setVisible(false);
	jPanelCol2.setPreferredSize(dmnsn0);
	jPanelCol3.setVisible(false);
	jPanelCol3.setPreferredSize(dmnsn0);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(true);
	jPanelCol5.setPreferredSize(dmnsn1);
	jButtonAltPag04.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAltPag04ActionPerformed

    private void jButtonAltPag05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltPag05ActionPerformed
        resetButtonColor();
	jPanelCol1.setVisible(false);
	jPanelCol1.setPreferredSize(dmnsn0);
	jPanelCol2.setVisible(false);
	jPanelCol2.setPreferredSize(dmnsn0);
	jPanelCol3.setVisible(false);
	jPanelCol3.setPreferredSize(dmnsn0);
	jPanelCol4.setVisible(false);
	jPanelCol4.setPreferredSize(dmnsn0);
	jPanelCol5.setVisible(true);
	jPanelCol5.setPreferredSize(dmnsn1);
	jButtonAltPag05.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAltPag05ActionPerformed

    private void lblAcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcoesMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblAcoesMouseClicked

    private void jPanelLine2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine2MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META01.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine2MouseClicked

    private void jPanelLine1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine1MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META02.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine1MouseClicked

    private void jPanelLine3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine3MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META03.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine3MouseClicked

    private void jPanelLine4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine4MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META04.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine4MouseClicked

    private void jPanelLine5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine5MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META05.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine5MouseClicked

    private void jPanelLine12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine12MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META06.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine12MouseClicked

    private void jPanelLine11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine11MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META07.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine11MouseClicked

    private void jPanelLine13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine13MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META08.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine13MouseClicked

    private void jPanelLine14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine14MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META09.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine14MouseClicked

    private void jPanelLine15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine15MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META10.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine15MouseClicked

    private void jPanelLine7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine7MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META11.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine7MouseClicked

    private void jPanelLine6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine6MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META12.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine6MouseClicked

    private void jPanelLine8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine8MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META13.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine8MouseClicked

    private void jPanelLine9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine9MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META14.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine9MouseClicked

    private void jPanelLine10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine10MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META15.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine10MouseClicked

    private void jPanelLine22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine22MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META16.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine22MouseClicked

    private void jPanelLine21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLine21MouseClicked
        // TODO add your handling code here:
	TelaContentMeta cm = new TelaContentMeta();
	cm.setNomeArquivo("META17.html");
	cm.setVisible(true);
    }//GEN-LAST:event_jPanelLine21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaMetas().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltPag01;
    private javax.swing.JButton jButtonAltPag02;
    private javax.swing.JButton jButtonAltPag03;
    private javax.swing.JButton jButtonAltPag04;
    private javax.swing.JButton jButtonAltPag05;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCol1;
    private javax.swing.JPanel jPanelCol2;
    private javax.swing.JPanel jPanelCol3;
    private javax.swing.JPanel jPanelCol4;
    private javax.swing.JPanel jPanelCol5;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLine1;
    private javax.swing.JPanel jPanelLine10;
    private javax.swing.JPanel jPanelLine11;
    private javax.swing.JPanel jPanelLine12;
    private javax.swing.JPanel jPanelLine13;
    private javax.swing.JPanel jPanelLine14;
    private javax.swing.JPanel jPanelLine15;
    private javax.swing.JPanel jPanelLine16;
    private javax.swing.JPanel jPanelLine17;
    private javax.swing.JPanel jPanelLine18;
    private javax.swing.JPanel jPanelLine19;
    private javax.swing.JPanel jPanelLine2;
    private javax.swing.JPanel jPanelLine20;
    private javax.swing.JPanel jPanelLine21;
    private javax.swing.JPanel jPanelLine22;
    private javax.swing.JPanel jPanelLine23;
    private javax.swing.JPanel jPanelLine24;
    private javax.swing.JPanel jPanelLine25;
    private javax.swing.JPanel jPanelLine3;
    private javax.swing.JPanel jPanelLine4;
    private javax.swing.JPanel jPanelLine5;
    private javax.swing.JPanel jPanelLine6;
    private javax.swing.JPanel jPanelLine7;
    private javax.swing.JPanel jPanelLine8;
    private javax.swing.JPanel jPanelLine9;
    public static javax.swing.JLabel lblAcoes;
    public static javax.swing.JLabel lblLogoOds;
    public static javax.swing.JLabel lblTituloOds;
    // End of variables declaration//GEN-END:variables
}
