package View;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author pedro
 */
public class TelaODS extends javax.swing.JFrame {

    /**
     * @return the nomeArquivo
     */
    public String getNomeArquivo() {
	return nomeArquivo;
    }

    /**
     * @param nomeArquivo the nomeArquivo to set
     */
    public void setNomeArquivo(String nomeArquivo) {
	this.nomeArquivo = nomeArquivo;
    }

    /**
     * @return the content
     */
    public String getContent() {
	return content;
    }

    /**
     * @param content the content to set
     */
    public void setContent(String content) {
	this.content = content;
    }

    /**
     * Creates new form TelaODS01
     */
    public TelaODS() {
	initComponents();
    }
    
    private String content;
    private String nomeArquivo;
    
    private void lerArquivo(String path){
	String cont = "";
	try {
	   FileReader fr = new FileReader(path);
	   BufferedReader lerArq = new BufferedReader(fr);
	   while(lerArq.ready()){
	       cont += lerArq.readLine();
	   }  
	   setContent(cont);
	} catch (IOException e) {
	    e.getMessage();
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lblLogoOds = new javax.swing.JLabel();
        lblTituloOds = new javax.swing.JLabel();
        lblAcoes = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setName("frmOds01"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.setMaximumSize(new java.awt.Dimension(1920, 200));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1000, 800));

        lblLogoOds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoOds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/LogoLogin64.png"))); // NOI18N
        lblLogoOds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogoOds.setPreferredSize(new java.awt.Dimension(100, 100));

        lblTituloOds.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTituloOds.setForeground(new java.awt.Color(80, 80, 80));
        lblTituloOds.setText("Geração do Amanhã");

        lblAcoes.setBackground(new java.awt.Color(80, 80, 80));
        lblAcoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAcoes.setForeground(new java.awt.Color(80, 80, 80));
        lblAcoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/progress_peq.png"))); // NOI18N
        lblAcoes.setText("Ir para as Acões");
        lblAcoes.setFocusable(false);
        lblAcoes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblAcoes.setMaximumSize(new java.awt.Dimension(100, 100));
        lblAcoes.setMinimumSize(new java.awt.Dimension(100, 100));
        lblAcoes.setPreferredSize(new java.awt.Dimension(230, 100));
        lblAcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcoesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(lblLogoOds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTituloOds, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogoOds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloOds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(700, Short.MAX_VALUE))
        );

        jPanelContent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelContent.setMaximumSize(new java.awt.Dimension(1920, 880));
        jPanelContent.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanelContent.setPreferredSize(new java.awt.Dimension(1000, 700));

        jScrollPane1.setBackground(new java.awt.Color(80, 80, 80));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1920, 880));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(975, 675));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(975, 675));

        tp.setEnabled(false);
        tp.setMaximumSize(new java.awt.Dimension(1920, 880));
        tp.setMinimumSize(new java.awt.Dimension(950, 750));
        tp.setPreferredSize(new java.awt.Dimension(950, 750));
        jScrollPane1.setViewportView(tp);

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
	tp.setContentType("text/html");
	String caminho = "src/view/resources/" + getNomeArquivo();
	System.out.println(caminho);
	lerArquivo(caminho);
	tp.setText(getContent());
	tp.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_formWindowOpened

    private void lblAcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcoesMouseClicked
        // TODO add your handling code here:
	TelaMetas meta = new TelaMetas();
	meta.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_lblAcoesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaODS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaODS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaODS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaODS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaODS().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblAcoes;
    public static javax.swing.JLabel lblLogoOds;
    public static javax.swing.JLabel lblTituloOds;
    private javax.swing.JTextPane tp;
    // End of variables declaration//GEN-END:variables
}
