/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;
import Model.LoginModel;
import static View.TelaPrincipal.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
	initComponents();
    }
    
    private void limpar(){
	txtUsuario.setText(null);
	txtSenha.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMinimized = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCadastrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName("frmLogin"); // NOI18N
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jPanelHeader.setBackground(new java.awt.Color(74, 128, 80));
        jPanelHeader.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanelHeader.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(900, 500));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(216, 216, 216));
        lblTitle.setText("Geração do Amanhã - Login");
        lblTitle.setMaximumSize(new java.awt.Dimension(450, 50));
        lblTitle.setMinimumSize(new java.awt.Dimension(450, 50));
        lblTitle.setPreferredSize(new java.awt.Dimension(450, 50));

        lblMinimized.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblMinimized.setForeground(new java.awt.Color(216, 216, 216));
        lblMinimized.setText("-");
        lblMinimized.setMaximumSize(new java.awt.Dimension(30, 50));
        lblMinimized.setMinimumSize(new java.awt.Dimension(30, 50));
        lblMinimized.setPreferredSize(new java.awt.Dimension(30, 50));
        lblMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizedMouseClicked(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(216, 216, 216));
        lblExit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(216, 216, 216));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setMaximumSize(new java.awt.Dimension(30, 50));
        lblExit.setMinimumSize(new java.awt.Dimension(30, 50));
        lblExit.setPreferredSize(new java.awt.Dimension(30, 50));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(lblMinimized, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimized, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 450, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelHeader);
        jPanelHeader.setBounds(0, 0, 900, 50);

        jPanelContent.setBackground(new java.awt.Color(119, 191, 86));
        jPanelContent.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanelContent.setMinimumSize(new java.awt.Dimension(900, 450));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/LogoLogin.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(120, 120, 120));
        lblUsuario.setText("Usuario");

        lblUsuario1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(120, 120, 120));
        lblUsuario1.setText("Senha");

        txtUsuario.setBackground(new java.awt.Color(216, 216, 216));
        txtUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuario.setToolTipText("Digite seu Usuário");

        txtSenha.setBackground(new java.awt.Color(216, 216, 216));
        txtSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSenha.setToolTipText("Digite sua senha");

        btnLogin.setBackground(new java.awt.Color(34, 167, 240));
        btnLogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(242, 242, 242));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Efetuar login");
        btnLogin.setPreferredSize(new java.awt.Dimension(100, 40));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(192, 57, 43));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(242, 242, 242));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar tentativa de login");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(216, 216, 216));
        lblCadastrar.setText("Clique aqui para fazer um novo cadastro. Cadastre - se");
        lblCadastrar.setToolTipText("Vá para tela de cadastro de usuários");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imgLogo)
                .addGap(46, 46, 46)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUsuario)
                        .addComponent(lblUsuario1)
                        .addComponent(txtUsuario)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCadastrar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanelContentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblUsuario, lblUsuario1});

        jPanelContentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnLogin});

        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imgLogo))
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))
                        .addGap(28, 28, 28)
                        .addComponent(lblCadastrar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelContentLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnLogin});

        getContentPane().add(jPanelContent);
        jPanelContent.setBounds(0, 50, 900, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        
	System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizedMouseClicked
        
	this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizedMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        
	limpar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        
	LoginModel login = new LoginModel();
	try {
	    if(login.validarLogin(txtUsuario.getText(), txtSenha.getText())){
		TelaPrincipal cad = new TelaPrincipal();
		lblNome.setText(login.getNome_logado());
		lblPontuacao.setText(Integer.toString(login.getPontuacao_logado()));
		cad.setVisible(true);
		cad.pack();
		cad.setLocationRelativeTo(null);
		cad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.dispose();
	    }else{
		JOptionPane.showMessageDialog(null,"Usuário e senha não cadastrados!");
	    }
	} catch (SQLException ex) {
	    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
	}
	
    }//GEN-LAST:event_btnLoginMouseClicked

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        
	TelaCadastro cad = new TelaCadastro();
	cad.setVisible(true);
	cad.pack();
	cad.setLocationRelativeTo(null);
	cad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	this.dispose();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaLogin().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimized;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
